-- Sobre Ruedas v2.8.0
-- Estabilización integral: cuentas, suspensiones, soporte, chat, cierre de viajes,
-- calificaciones, ganancias y bloqueo real de conductores no operables.
-- Ejecutar UNA sola vez después de v2.7.0 o v2.7.1.

begin;
create extension if not exists pgcrypto;

-- Columnas operativas compatibles con instalaciones anteriores.
alter table public.profiles add column if not exists suspended_until timestamptz;
alter table public.profiles add column if not exists suspension_reason text;
alter table public.profiles add column if not exists suspended_at timestamptz;
alter table public.profiles add column if not exists suspended_by text;
alter table public.profiles add column if not exists is_online boolean not null default false;
alter table public.profiles add column if not exists last_seen_at timestamptz;
alter table public.profiles add column if not exists photo_url text;
alter table public.profiles add column if not exists vehicle_photo_url text;
alter table public.profiles add column if not exists vehicle_make text;
alter table public.profiles add column if not exists vehicle_model text;
alter table public.profiles add column if not exists vehicle_year text;
alter table public.profiles add column if not exists vehicle_color text;
alter table public.profiles add column if not exists vehicle_plate text;
alter table public.profiles add column if not exists vehicle_capacity integer;
alter table public.profiles add column if not exists deactivated_at timestamptz;
alter table public.profiles add column if not exists deactivated_by text;
alter table public.profiles add column if not exists deactivation_reason text;
alter table public.rides add column if not exists offered_driver_id text;
alter table public.rides add column if not exists offered_at timestamptz;
alter table public.rides add column if not exists offer_expires_at timestamptz;
alter table public.rides add column if not exists cancel_reason text;
alter table public.rides add column if not exists admin_note text;
alter table public.rides add column if not exists last_event_at timestamptz;
alter table public.rides add column if not exists finished_at timestamptz;
alter table public.rides add column if not exists canceled_at timestamptz;
alter table public.rides add column if not exists canceled_by text;
alter table public.rides add column if not exists driver_lat numeric;
alter table public.rides add column if not exists driver_lng numeric;
alter table public.rides add column if not exists driver_last_update_at timestamptz;
alter table public.rides add column if not exists passenger_photo text;
alter table public.rides add column if not exists driver_photo text;
alter table public.rides add column if not exists driver_rating numeric;
alter table public.rides add column if not exists driver_vehicle_make text;
alter table public.rides add column if not exists driver_vehicle_model text;
alter table public.rides add column if not exists driver_vehicle_year text;
alter table public.rides add column if not exists driver_vehicle_color text;
alter table public.rides add column if not exists driver_vehicle_plate text;
alter table public.rides add column if not exists rating numeric;
alter table public.rides add column if not exists rating_comment text;
alter table public.rides add column if not exists rated_at timestamptz;
alter table public.rides add column if not exists support_flag boolean not null default false;
alter table public.rides add column if not exists admin_finished_at timestamptz;
alter table public.rides add column if not exists admin_finished_by text;

create table if not exists public.deleted_accounts (
  id uuid primary key default gen_random_uuid(),
  device_id text not null,
  role text not null,
  email_hash text,
  phone_hash text,
  reason text not null,
  deleted_by text,
  deleted_at timestamptz not null default now()
);
create unique index if not exists deleted_accounts_device_role_uidx on public.deleted_accounts(device_id,role);
create index if not exists deleted_accounts_email_hash_v280_idx on public.deleted_accounts(email_hash) where email_hash is not null;
create index if not exists deleted_accounts_phone_hash_v280_idx on public.deleted_accounts(phone_hash) where phone_hash is not null;
alter table public.deleted_accounts enable row level security;
revoke all on table public.deleted_accounts from anon,authenticated;

create table if not exists public.ride_messages (
  id bigint generated by default as identity primary key,
  ride_id text not null,
  sender_id text not null,
  sender_role text not null,
  message text not null,
  message_type text not null default 'text',
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists ride_messages_ride_created_v280_idx on public.ride_messages(ride_id,created_at);

create table if not exists public.support_cases (
  id uuid primary key default gen_random_uuid(),
  case_number bigint generated by default as identity unique,
  created_by_id text not null,
  created_by_role text not null,
  related_ride_id text,
  category text not null,
  subject text not null,
  description text not null,
  priority text not null default 'normal',
  status text not null default 'open',
  assigned_to text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.support_messages (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.support_cases(id) on delete cascade,
  sender_id text not null,
  sender_role text not null,
  message text not null,
  created_at timestamptz not null default now()
);
create index if not exists support_cases_status_v280_idx on public.support_cases(status,priority,created_at desc);
create index if not exists support_cases_creator_v280_idx on public.support_cases(created_by_id,created_at desc);
create index if not exists support_messages_case_v280_idx on public.support_messages(case_id,created_at);

create table if not exists public.driver_reports (
  id uuid primary key default gen_random_uuid(),
  ride_id text,
  driver_id text,
  driver_name text,
  passenger_id text,
  passenger_name text,
  rating integer,
  passenger_comment text,
  reviewed boolean not null default false,
  reviewed_at timestamptz,
  reviewed_by text,
  risk_level text default 'green',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.driver_reports add column if not exists ride_id text;
alter table public.driver_reports add column if not exists driver_id text;
alter table public.driver_reports add column if not exists driver_name text;
alter table public.driver_reports add column if not exists passenger_id text;
alter table public.driver_reports add column if not exists passenger_name text;
alter table public.driver_reports add column if not exists rating integer;
alter table public.driver_reports add column if not exists passenger_comment text;
alter table public.driver_reports add column if not exists reviewed boolean default false;
alter table public.driver_reports add column if not exists reviewed_at timestamptz;
alter table public.driver_reports add column if not exists reviewed_by text;
alter table public.driver_reports add column if not exists risk_level text default 'green';
alter table public.driver_reports add column if not exists created_at timestamptz default now();
alter table public.driver_reports add column if not exists updated_at timestamptz default now();
delete from public.driver_reports a using public.driver_reports b
where a.ride_id is not null and b.ride_id is not null and a.ride_id::text=b.ride_id::text
  and (coalesce(a.updated_at,a.created_at),a.ctid)<(coalesce(b.updated_at,b.created_at),b.ctid);
create unique index if not exists driver_reports_ride_v280_uidx on public.driver_reports(ride_id) where ride_id is not null;

create or replace function public.sr_hash_contact_v280(p_value text)
returns text language sql immutable strict as $$
  select encode(digest(lower(regexp_replace(trim(p_value),'\s+','','g')),'sha256'),'hex')
$$;

create or replace function public.is_deleted_account_v280(
  p_device_id text,p_role text,p_email text default null,p_phone text default null
)
returns boolean language sql security definer set search_path=public as $$
  select exists(
    select 1 from public.deleted_accounts d
    where d.role=p_role and (
      d.device_id=p_device_id
      or (nullif(trim(coalesce(p_email,'')),'') is not null and d.email_hash=public.sr_hash_contact_v280(p_email))
      or (nullif(trim(coalesce(p_phone,'')),'') is not null and d.phone_hash=public.sr_hash_contact_v280(p_phone))
    )
  )
$$;

create or replace function public.prevent_deleted_account_recreation_v280()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if public.is_deleted_account_v280(new.device_id,new.role,new.email,new.phone) then
    raise exception using errcode='P0001',message='ACCOUNT_PERMANENTLY_DELETED';
  end if;
  return new;
end;
$$;
drop trigger if exists profiles_prevent_deleted_recreation_v271 on public.profiles;
drop trigger if exists profiles_prevent_deleted_recreation_v280 on public.profiles;
create trigger profiles_prevent_deleted_recreation_v280
before insert on public.profiles for each row execute function public.prevent_deleted_account_recreation_v280();

-- Regla central de operabilidad.
create or replace function public.enforce_profile_operability_v280()
returns trigger language plpgsql set search_path=public as $$
begin
  if new.status is distinct from 'active'
     or new.approval_status in ('deleted','rejected')
     or (new.suspended_until is not null and new.suspended_until>now()) then
    new.is_online:=false;
  end if;
  return new;
end;
$$;
drop trigger if exists profiles_enforce_operability on public.profiles;
drop trigger if exists profiles_enforce_operability_v271 on public.profiles;
drop trigger if exists profiles_enforce_operability_v280 on public.profiles;
create trigger profiles_enforce_operability_v280
before insert or update on public.profiles for each row execute function public.enforce_profile_operability_v280();

-- Impide que un conductor suspendido, desaprobado o eliminado acepte/continúe viajes.
create or replace function public.enforce_ride_driver_operability_v280()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_ok boolean;
begin
  if new.offered_driver_id is not null and new.status='searching' then
    select exists(select 1 from public.profiles p where p.role='driver'
      and (p.device_id=new.offered_driver_id or p.id::text=new.offered_driver_id)
      and p.status='active' and p.approval_status='approved'
      and (p.suspended_until is null or p.suspended_until<=now())
      and coalesce(p.is_online,false)=true) into v_ok;
    if not coalesce(v_ok,false) then
      new.offered_driver_id:=null;new.offered_at:=null;new.offer_expires_at:=null;
    end if;
  end if;
  if new.driver_id is not null and new.status in ('accepted','arrived','in_progress') then
    select exists(select 1 from public.profiles p where p.role='driver'
      and (p.device_id=new.driver_id or p.id::text=new.driver_id)
      and p.status='active' and p.approval_status='approved'
      and (p.suspended_until is null or p.suspended_until<=now())) into v_ok;
    if not coalesce(v_ok,false) then
      raise exception using errcode='P0001',message='DRIVER_NOT_OPERABLE';
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists rides_enforce_driver_operability_v280 on public.rides;
create trigger rides_enforce_driver_operability_v280
before insert or update of status,driver_id,offered_driver_id on public.rides
for each row execute function public.enforce_ride_driver_operability_v280();


-- El pasajero suspendido, desactivado o eliminado tampoco puede crear solicitudes nuevas.
create or replace function public.enforce_ride_passenger_operability_v280()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_ok boolean;
begin
  if new.status='searching' and new.passenger_id is not null then
    select exists(select 1 from public.profiles p where p.role='passenger'
      and (p.device_id=new.passenger_id::text or p.id::text=new.passenger_id::text)
      and p.status='active' and coalesce(p.approval_status,'approved') not in ('deleted','rejected')
      and (p.suspended_until is null or p.suspended_until<=now())) into v_ok;
    if not coalesce(v_ok,false) then
      raise exception using errcode='P0001',message='PASSENGER_NOT_OPERABLE';
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists rides_enforce_passenger_operability_v280 on public.rides;
create trigger rides_enforce_passenger_operability_v280
before insert or update of status,passenger_id on public.rides
for each row execute function public.enforce_ride_passenger_operability_v280();

-- Suspender, levantar suspensión, desactivar o reactivar una cuenta.
create or replace function public.admin_set_account_state_v280(
  p_person_id text,p_role text,p_action text,p_until timestamptz,p_reason text,p_admin_name text,p_admin_code text
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_profile public.profiles;
  v_keys text[];
  v_now timestamptz:=now();
  v_canceled integer:=0;
begin
  if p_admin_code is distinct from 'RUEDA2026' then raise exception using errcode='P0001',message='ADMIN_CODE_INVALID'; end if;
  if p_role not in ('driver','passenger') then raise exception using errcode='P0001',message='ROLE_INVALID'; end if;
  if p_action not in ('suspend','unsuspend','deactivate','reactivate') then raise exception using errcode='P0001',message='ACCOUNT_ACTION_INVALID'; end if;
  select * into v_profile from public.profiles p
  where p.role=p_role and (p.device_id=p_person_id or p.id::text=p_person_id)
  order by p.updated_at desc nulls last limit 1 for update;
  if not found then raise exception using errcode='P0001',message='PROFILE_NOT_FOUND'; end if;
  select array_agg(distinct x) into v_keys from unnest(array[p_person_id,v_profile.device_id,v_profile.id::text]) x where x is not null and x<>'';

  if p_action='suspend' then
    if p_until is null or p_until<=v_now then raise exception using errcode='P0001',message='SUSPENSION_DATE_INVALID'; end if;
    if nullif(trim(coalesce(p_reason,'')),'') is null then raise exception using errcode='P0001',message='SUSPENSION_REASON_REQUIRED'; end if;
    update public.profiles set suspended_until=p_until,suspension_reason=trim(p_reason),suspended_at=v_now,
      suspended_by=coalesce(nullif(trim(p_admin_name),''),'administración'),is_online=false,updated_at=v_now where id=v_profile.id;
    update public.rides set status='canceled',canceled_at=coalesce(canceled_at,v_now),canceled_by='admin',
      cancel_reason='Cuenta suspendida: '||trim(p_reason),admin_note='Suspensión administrativa',
      offered_driver_id=null,offered_at=null,offer_expires_at=null,last_event_at=v_now,updated_at=v_now
    where status in ('searching','accepted','arrived','in_progress')
      and ((p_role='driver' and driver_id::text=any(v_keys)) or (p_role='passenger' and passenger_id::text=any(v_keys)));
    get diagnostics v_canceled=row_count;
  elsif p_action='unsuspend' then
    update public.profiles set suspended_until=null,suspension_reason=null,suspended_at=null,suspended_by=null,is_online=false,updated_at=v_now where id=v_profile.id;
  elsif p_action='deactivate' then
    if nullif(trim(coalesce(p_reason,'')),'') is null then raise exception using errcode='P0001',message='DEACTIVATION_REASON_REQUIRED'; end if;
    update public.profiles set approval_status='rejected',is_online=false,deactivated_at=v_now,
      deactivated_by=coalesce(nullif(trim(p_admin_name),''),'administración'),deactivation_reason=trim(p_reason),updated_at=v_now where id=v_profile.id;
    update public.rides set status='canceled',canceled_at=coalesce(canceled_at,v_now),canceled_by='admin',
      cancel_reason='Cuenta desactivada: '||trim(p_reason),admin_note='Desactivación administrativa',
      offered_driver_id=null,offered_at=null,offer_expires_at=null,last_event_at=v_now,updated_at=v_now
    where status in ('searching','accepted','arrived','in_progress')
      and ((p_role='driver' and driver_id::text=any(v_keys)) or (p_role='passenger' and passenger_id::text=any(v_keys)));
    get diagnostics v_canceled=row_count;
  else
    update public.profiles set status='active',approval_status=case when p_role='driver' then 'pending' else 'approved' end,
      is_online=false,deactivated_at=null,deactivated_by=null,deactivation_reason=null,updated_at=v_now where id=v_profile.id;
  end if;

  begin
    insert into public.admin_action_log(action,target_id,target_role,reason,admin_name,metadata,created_at)
    values(p_action||'_'||p_role,coalesce(v_profile.device_id,p_person_id),p_role,nullif(trim(coalesce(p_reason,'')),''),p_admin_name,
      jsonb_build_object('until',p_until,'rides_canceled',v_canceled),v_now);
  exception when others then null;
  end;
  return jsonb_build_object('ok',true,'action',p_action,'role',p_role,'rides_canceled',v_canceled);
end;
$$;

-- Eliminación definitiva robusta. Conserva únicamente un identificador técnico/hash para impedir recreación automática.
create or replace function public.admin_delete_account_v280(
  p_person_id text,p_role text,p_reason text,p_admin_name text,p_admin_code text
)
returns jsonb language plpgsql security definer set search_path=public,storage as $$
declare
  v_profile public.profiles;
  v_keys text[];
  v_ride_ids text[]:=array[]::text[];
  v_rides_count integer:=0;
  v_media_count integer:=0;
  v_fk record;
  v_sql text;
begin
  if p_admin_code is distinct from 'RUEDA2026' then raise exception using errcode='P0001',message='ADMIN_CODE_INVALID'; end if;
  if p_role not in ('driver','passenger') then raise exception using errcode='P0001',message='ROLE_INVALID'; end if;
  if nullif(trim(coalesce(p_reason,'')),'') is null then raise exception using errcode='P0001',message='DELETE_REASON_REQUIRED'; end if;

  select * into v_profile from public.profiles p
  where p.role=p_role and (p.device_id=p_person_id or p.id::text=p_person_id)
  order by p.updated_at desc nulls last limit 1 for update;
  if not found then
    if exists(select 1 from public.deleted_accounts d where d.role=p_role and d.device_id=p_person_id) then
      return jsonb_build_object('ok',true,'already_deleted',true,'rides_deleted',0,'media_deleted',0);
    end if;
    raise exception using errcode='P0001',message='PROFILE_NOT_FOUND';
  end if;
  select array_agg(distinct x) into v_keys from unnest(array[p_person_id,v_profile.device_id,v_profile.id::text]) x where x is not null and x<>'';

  insert into public.deleted_accounts(device_id,role,email_hash,phone_hash,reason,deleted_by,deleted_at)
  values(coalesce(v_profile.device_id,p_person_id),p_role,
    case when nullif(trim(coalesce(v_profile.email,'')),'') is null then null else public.sr_hash_contact_v280(v_profile.email) end,
    case when nullif(trim(coalesce(v_profile.phone,'')),'') is null then null else public.sr_hash_contact_v280(v_profile.phone) end,
    trim(p_reason),coalesce(nullif(trim(p_admin_name),''),'administración'),now())
  on conflict(device_id,role) do update set email_hash=excluded.email_hash,phone_hash=excluded.phone_hash,
    reason=excluded.reason,deleted_by=excluded.deleted_by,deleted_at=excluded.deleted_at;

  select coalesce(array_agg(r.id::text),array[]::text[]) into v_ride_ids from public.rides r
  where (p_role='driver' and r.driver_id::text=any(v_keys)) or (p_role='passenger' and r.passenger_id::text=any(v_keys));
  v_rides_count:=coalesce(array_length(v_ride_ids,1),0);

  begin delete from public.ride_messages where ride_id::text=any(v_ride_ids) or sender_id::text=any(v_keys); exception when others then null; end;
  begin delete from public.ride_events where ride_id::text=any(v_ride_ids) or actor_id::text=any(v_keys); exception when others then null; end;
  begin delete from public.ride_offer_attempts where ride_id::text=any(v_ride_ids) or driver_id::text=any(v_keys); exception when others then null; end;
  begin delete from public.support_cases where created_by_id::text=any(v_keys) or related_ride_id::text=any(v_ride_ids); exception when others then null; end;

  if to_regclass('public.driver_reports') is not null then
    v_sql:='delete from public.driver_reports where false';
    if exists(select 1 from information_schema.columns where table_schema='public' and table_name='driver_reports' and column_name='ride_id') then v_sql:=v_sql||' or ride_id::text=any($1)'; end if;
    if exists(select 1 from information_schema.columns where table_schema='public' and table_name='driver_reports' and column_name='driver_id') and p_role='driver' then v_sql:=v_sql||' or driver_id::text=any($2)'; end if;
    if exists(select 1 from information_schema.columns where table_schema='public' and table_name='driver_reports' and column_name='passenger_id') and p_role='passenger' then v_sql:=v_sql||' or passenger_id::text=any($2)'; end if;
    execute v_sql using v_ride_ids,v_keys;
  end if;

  -- Cualquier tabla adicional con FK a rides se limpia antes de borrar viajes.
  for v_fk in
    select ns.nspname schema_name,cl.relname table_name,att.attname column_name
    from pg_constraint con join pg_class cl on cl.oid=con.conrelid join pg_namespace ns on ns.oid=cl.relnamespace
    join unnest(con.conkey) ck(attnum) on true join pg_attribute att on att.attrelid=con.conrelid and att.attnum=ck.attnum
    where con.contype='f' and con.confrelid='public.rides'::regclass and con.conrelid<>con.confrelid and array_length(con.conkey,1)=1
  loop
    begin execute format('delete from %I.%I where %I::text=any($1)',v_fk.schema_name,v_fk.table_name,v_fk.column_name) using v_ride_ids; exception when others then null; end;
  end loop;
  delete from public.rides where id::text=any(v_ride_ids);

  begin
    with removed as (
      delete from storage.objects where bucket_id='sobre-ruedas-media' and (
        name like '%/'||coalesce(v_profile.device_id,'__none__')||'/%' or name like '%/'||v_profile.id::text||'/%') returning 1
    ) select count(*) into v_media_count from removed;
  exception when others then v_media_count:=0;
  end;

  -- Cualquier tabla adicional con FK a profiles se limpia con comparación textual compatible.
  for v_fk in
    select ns.nspname schema_name,cl.relname table_name,att.attname column_name
    from pg_constraint con join pg_class cl on cl.oid=con.conrelid join pg_namespace ns on ns.oid=cl.relnamespace
    join unnest(con.conkey) ck(attnum) on true join pg_attribute att on att.attrelid=con.conrelid and att.attnum=ck.attnum
    where con.contype='f' and con.confrelid='public.profiles'::regclass and con.conrelid<>con.confrelid and array_length(con.conkey,1)=1
  loop
    begin execute format('delete from %I.%I where %I::text=any($1)',v_fk.schema_name,v_fk.table_name,v_fk.column_name) using v_keys; exception when others then null; end;
  end loop;
  delete from public.profiles where id=v_profile.id;

  begin
    insert into public.admin_action_log(action,target_id,target_role,reason,admin_name,metadata,created_at)
    values('permanent_delete_'||p_role,'[eliminado]',p_role,trim(p_reason),p_admin_name,
      jsonb_build_object('rides_deleted',v_rides_count,'media_deleted',v_media_count),now());
  exception when others then null;
  end;
  return jsonb_build_object('ok',true,'role',p_role,'rides_deleted',v_rides_count,'media_deleted',v_media_count);
end;
$$;

create or replace function public.admin_resolve_ride_v280(
  p_ride_id text,p_action text,p_reason text,p_admin_name text,p_admin_code text
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_ride public.rides;v_now timestamptz:=now();
begin
  if p_admin_code is distinct from 'RUEDA2026' then raise exception using errcode='P0001',message='ADMIN_CODE_INVALID'; end if;
  if p_action not in ('finish','cancel') then raise exception using errcode='P0001',message='ADMIN_RIDE_ACTION_INVALID'; end if;
  if nullif(trim(coalesce(p_reason,'')),'') is null then raise exception using errcode='P0001',message='ADMIN_RIDE_REASON_REQUIRED'; end if;
  select * into v_ride from public.rides where id::text=p_ride_id for update;
  if not found then raise exception using errcode='P0001',message='RIDE_NOT_FOUND'; end if;
  if p_action='finish' then
    if v_ride.status not in ('accepted','arrived','in_progress') then raise exception using errcode='P0001',message='RIDE_CANNOT_BE_FINISHED_FROM_CURRENT_STATUS'; end if;
    update public.rides set status='finished',finished_at=coalesce(finished_at,v_now),admin_finished_at=v_now,
      admin_finished_by=coalesce(nullif(trim(p_admin_name),''),'administración'),admin_note=trim(p_reason),
      offered_driver_id=null,offered_at=null,offer_expires_at=null,last_event_at=v_now,updated_at=v_now
    where id::text=p_ride_id returning * into v_ride;
  else
    if v_ride.status not in ('searching','accepted','arrived','in_progress') then raise exception using errcode='P0001',message='RIDE_CANNOT_BE_CANCELED_FROM_CURRENT_STATUS'; end if;
    update public.rides set status='canceled',canceled_at=coalesce(canceled_at,v_now),canceled_by='admin',cancel_reason=trim(p_reason),
      admin_note=trim(p_reason),offered_driver_id=null,offered_at=null,offer_expires_at=null,last_event_at=v_now,updated_at=v_now
    where id::text=p_ride_id returning * into v_ride;
  end if;
  begin insert into public.ride_events(ride_id,event_type,actor_role,actor_id,metadata)
    values(p_ride_id,'admin_'||p_action,'admin',p_admin_name,jsonb_build_object('reason',trim(p_reason),'status',v_ride.status));
  exception when others then null; end;
  return jsonb_build_object('ok',true,'ride_id',p_ride_id,'status',v_ride.status);
end;
$$;

create or replace function public.create_support_case_v280(
  p_creator_id text,p_creator_role text,p_ride_id text,p_category text,p_subject text,p_description text,p_priority text default 'normal'
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_case public.support_cases;
begin
  if p_creator_role not in ('passenger','driver') then raise exception using errcode='P0001',message='SUPPORT_ROLE_INVALID'; end if;
  if nullif(trim(coalesce(p_creator_id,'')),'') is null then raise exception using errcode='P0001',message='SUPPORT_CREATOR_REQUIRED'; end if;
  if nullif(trim(coalesce(p_category,'')),'') is null or length(trim(coalesce(p_description,'')))<8 then raise exception using errcode='P0001',message='SUPPORT_DETAILS_REQUIRED'; end if;
  insert into public.support_cases(created_by_id,created_by_role,related_ride_id,category,subject,description,priority,status,created_at,updated_at)
  values(p_creator_id,p_creator_role,nullif(trim(coalesce(p_ride_id,'')),''),trim(p_category),
    coalesce(nullif(trim(coalesce(p_subject,'')),''),trim(p_category)),trim(p_description),
    case when p_priority in ('normal','high','emergency') then p_priority else 'normal' end,'open',now(),now()) returning * into v_case;
  insert into public.support_messages(case_id,sender_id,sender_role,message,created_at)
  values(v_case.id,p_creator_id,p_creator_role,trim(p_description),now());
  if nullif(trim(coalesce(p_ride_id,'')),'') is not null then update public.rides set support_flag=true,updated_at=now() where id::text=p_ride_id; end if;
  return to_jsonb(v_case);
end;
$$;

create or replace function public.submit_ride_rating_v280(
  p_ride_id text,p_passenger_id text,p_rating integer,p_comment text default null
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_ride public.rides;
begin
  if p_rating<1 or p_rating>5 then raise exception using errcode='P0001',message='RATING_INVALID'; end if;
  select * into v_ride from public.rides r where r.id::text=p_ride_id and r.status='finished'
    and (r.passenger_id::text=p_passenger_id or exists(select 1 from public.profiles p where p.role='passenger' and p.device_id=p_passenger_id and p.id::text=r.passenger_id::text)) for update;
  if not found then raise exception using errcode='P0001',message='RIDE_NOT_FOUND_OR_NOT_RATEABLE'; end if;
  if v_ride.rating is not null then return jsonb_build_object('ok',true,'already_rated',true,'rating',v_ride.rating); end if;
  update public.rides set rating=p_rating,rating_comment=nullif(trim(coalesce(p_comment,'')),''),rated_at=now(),updated_at=now() where id=v_ride.id returning * into v_ride;
  if p_rating<=3 then
    insert into public.driver_reports(ride_id,driver_id,driver_name,passenger_id,passenger_name,rating,passenger_comment,reviewed,risk_level,created_at,updated_at)
    values(v_ride.id::text,v_ride.driver_id,v_ride.driver_name,v_ride.passenger_id,v_ride.passenger_name,p_rating,nullif(trim(coalesce(p_comment,'')),''),false,'green',now(),now())
    on conflict(ride_id) where ride_id is not null do update set rating=excluded.rating,passenger_comment=excluded.passenger_comment,updated_at=now();
  end if;
  return jsonb_build_object('ok',true,'rating',p_rating);
end;
$$;

create or replace function public.driver_earnings_summary_v280(p_driver_id text)
returns jsonb language sql security definer set search_path=public as $$
  with keys as (
    select p_driver_id key
    union
    select p.id::text from public.profiles p where p.role='driver' and (p.device_id=p_driver_id or p.id::text=p_driver_id)
    union
    select p.device_id from public.profiles p where p.role='driver' and (p.device_id=p_driver_id or p.id::text=p_driver_id)
  ),base as (
    select coalesce(r.price,0)::numeric amount,coalesce(r.finished_at,r.updated_at,r.created_at) completed_at
    from public.rides r where r.driver_id::text in (select key from keys where key is not null) and r.status='finished'
  ),bounds as (
    select (date_trunc('day',now() at time zone 'America/Havana') at time zone 'America/Havana') day_start,
      (date_trunc('week',now() at time zone 'America/Havana') at time zone 'America/Havana') week_start,
      (date_trunc('month',now() at time zone 'America/Havana') at time zone 'America/Havana') month_start
  )
  select jsonb_build_object('today',coalesce(sum(amount) filter(where completed_at>=day_start),0),
    'week',coalesce(sum(amount) filter(where completed_at>=week_start),0),
    'month',coalesce(sum(amount) filter(where completed_at>=month_start),0),
    'trips_today',count(*) filter(where completed_at>=day_start)) from base cross join bounds
$$;

update public.profiles set is_online=false,updated_at=now()
where status is distinct from 'active' or approval_status in ('deleted','rejected') or (suspended_until is not null and suspended_until>now());

-- Permisos y políticas de la arquitectura beta actual.
grant execute on function public.is_deleted_account_v280(text,text,text,text) to anon,authenticated;
grant execute on function public.admin_set_account_state_v280(text,text,text,timestamptz,text,text,text) to anon,authenticated;
grant execute on function public.admin_delete_account_v280(text,text,text,text,text) to anon,authenticated;
grant execute on function public.admin_resolve_ride_v280(text,text,text,text,text) to anon,authenticated;
grant execute on function public.create_support_case_v280(text,text,text,text,text,text,text) to anon,authenticated;
grant execute on function public.submit_ride_rating_v280(text,text,integer,text) to anon,authenticated;
grant execute on function public.driver_earnings_summary_v280(text) to anon,authenticated;

grant select,insert,update,delete on table public.ride_messages to anon,authenticated;
grant select,insert,update,delete on table public.support_cases to anon,authenticated;
grant select,insert,update,delete on table public.support_messages to anon,authenticated;
grant select,insert,update,delete on table public.driver_reports to anon,authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;

alter table public.ride_messages enable row level security;
alter table public.support_cases enable row level security;
alter table public.support_messages enable row level security;
alter table public.driver_reports enable row level security;
drop policy if exists beta_ride_messages_read on public.ride_messages;
drop policy if exists beta_ride_messages_v280 on public.ride_messages;
create policy beta_ride_messages_v280 on public.ride_messages for all to anon,authenticated using(true) with check(true);
drop policy if exists beta_support_cases on public.support_cases;
drop policy if exists beta_support_cases_v280 on public.support_cases;
create policy beta_support_cases_v280 on public.support_cases for all to anon,authenticated using(true) with check(true);
drop policy if exists beta_support_messages on public.support_messages;
drop policy if exists beta_support_messages_v280 on public.support_messages;
create policy beta_support_messages_v280 on public.support_messages for all to anon,authenticated using(true) with check(true);
drop policy if exists beta_driver_reports_v280 on public.driver_reports;
create policy beta_driver_reports_v280 on public.driver_reports for all to anon,authenticated using(true) with check(true);

do $$ begin alter publication supabase_realtime add table public.rides; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.profiles; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.ride_messages; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.support_cases; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.support_messages; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.driver_reports; exception when duplicate_object then null; end $$;

alter table public.rides replica identity full;
alter table public.profiles replica identity full;
alter table public.ride_messages replica identity full;
alter table public.support_cases replica identity full;
alter table public.support_messages replica identity full;
alter table public.driver_reports replica identity full;

notify pgrst,'reload schema';
commit;
