-- Sobre Ruedas v2.4.2 · Corrección de perfiles y aprobación administrativa
-- Migración segura e idempotente desde v2.4.1.
-- No borra viajes, usuarios, conductores, reportes ni tarifas.

begin;

create extension if not exists pgcrypto;

do $$
begin
  if to_regclass('public.profiles') is null then
    raise exception 'No existe public.profiles. Ejecuta primero ACTUALIZAR_SUPABASE_v2.4.1.sql.';
  end if;
end
$$;

-- PostgREST necesita una restricción única completa para ON CONFLICT(device_id).
-- Los índices UNIQUE permiten varios NULL, por lo que no hace falta un índice parcial.
drop index if exists public.profiles_device_id_uidx;
create unique index if not exists profiles_device_id_uidx
  on public.profiles(device_id);

-- La versión beta usa una identidad local por dispositivo y no Supabase Auth.
-- Se restauran únicamente los permisos necesarios para crear y actualizar perfiles.
grant select,insert,update,delete on table public.profiles to anon,authenticated;

alter table public.profiles enable row level security;

drop policy if exists "Administradores actualizan perfiles" on public.profiles;
drop policy if exists "Panel administra perfiles" on public.profiles;
drop policy if exists beta_profiles on public.profiles;

create policy beta_profiles
  on public.profiles
  for all
  to anon,authenticated
  using(true)
  with check(true);

-- Garantiza las columnas que utilizan la aplicación y el panel.
alter table public.profiles add column if not exists approval_status text default 'pending';
alter table public.profiles add column if not exists approved_at timestamptz;
alter table public.profiles add column if not exists approved_by text;
alter table public.profiles add column if not exists rejection_reason text;
alter table public.profiles add column if not exists is_online boolean default false;
alter table public.profiles add column if not exists last_seen_at timestamptz;
alter table public.profiles add column if not exists updated_at timestamptz default now();

update public.profiles
set approval_status=case
      when status='deleted' then 'deleted'
      when status='blocked' and role='driver' then 'rejected'
      when role='driver' and approval_status is null then 'pending'
      when role<>'driver' and approval_status is null then 'approved'
      else approval_status
    end,
    is_online=coalesce(is_online,false),
    updated_at=coalesce(updated_at,now());

-- Auditoría administrativa de la beta.
create table if not exists public.admin_action_log (
  id bigint generated by default as identity primary key,
  action text not null,
  target_id text not null,
  target_role text,
  reason text,
  admin_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

grant select,insert on table public.admin_action_log to anon,authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;
alter table public.admin_action_log enable row level security;
drop policy if exists beta_admin_action_log_read on public.admin_action_log;
drop policy if exists beta_admin_action_log_insert on public.admin_action_log;
create policy beta_admin_action_log_read on public.admin_action_log for select to anon,authenticated using(true);
create policy beta_admin_action_log_insert on public.admin_action_log for insert to anon,authenticated with check(true);

-- Realtime de perfiles.
do $$
begin
  alter publication supabase_realtime add table public.profiles;
exception when duplicate_object then null;
end
$$;

alter table public.profiles replica identity full;
notify pgrst,'reload schema';

commit;
