-- Sobre Ruedas v2.7.0 · Estabilidad operativa, chat, soporte y llamadas privadas por internet
-- Ejecutar UNA sola vez después de instalar la v2.6.0.
-- Migración idempotente: conserva los datos existentes.

begin;
create extension if not exists pgcrypto;

do $$ begin
  if to_regclass('public.profiles') is null or to_regclass('public.rides') is null then
    raise exception 'Faltan las tablas base profiles/rides. Instala primero Sobre Ruedas v2.6.0.';
  end if;
end $$;

-- Comunicación privada asociada a cada viaje.
alter table public.rides add column if not exists communication_token uuid default gen_random_uuid();
alter table public.rides add column if not exists admin_finished_at timestamptz;
alter table public.rides add column if not exists admin_finished_by text;
alter table public.rides add column if not exists support_flag boolean not null default false;
update public.rides set communication_token=gen_random_uuid() where communication_token is null;
create unique index if not exists rides_communication_token_uidx on public.rides(communication_token);


-- Tablas auxiliares requeridas por el flujo atómico. Se crean solo si faltan.
create table if not exists public.ride_events (
  id bigint generated by default as identity primary key,
  ride_id text,
  event_type text not null,
  actor_role text,
  actor_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists ride_events_ride_idx on public.ride_events(ride_id,created_at desc);
create table if not exists public.ride_offer_attempts (
  id bigint generated by default as identity primary key,
  ride_id text not null,
  driver_id text not null,
  outcome text not null default 'declined',
  created_at timestamptz not null default now()
);
create index if not exists ride_offer_attempts_lookup_idx on public.ride_offer_attempts(ride_id,driver_id,created_at desc);

create table if not exists public.ride_messages (
  id bigint generated by default as identity primary key,
  ride_id text not null,
  sender_id text not null,
  sender_role text not null check(sender_role in ('passenger','driver','system')),
  message text not null,
  message_type text not null default 'text' check(message_type in ('text','quick','system','image','call')),
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists ride_messages_ride_created_idx on public.ride_messages(ride_id,created_at);
create index if not exists ride_messages_unread_idx on public.ride_messages(ride_id,read_at) where read_at is null;

create table if not exists public.support_cases (
  id uuid primary key default gen_random_uuid(),
  case_number bigint generated by default as identity unique,
  created_by_id text not null,
  created_by_role text not null check(created_by_role in ('passenger','driver','admin')),
  related_ride_id text,
  category text not null,
  subject text not null,
  description text not null,
  priority text not null default 'normal' check(priority in ('normal','high','emergency')),
  status text not null default 'open' check(status in ('open','in_review','resolved','closed')),
  assigned_to text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists support_cases_status_priority_idx on public.support_cases(status,priority,created_at desc);
create index if not exists support_cases_creator_idx on public.support_cases(created_by_id,created_at desc);
create index if not exists support_cases_ride_idx on public.support_cases(related_ride_id);

create table if not exists public.support_messages (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.support_cases(id) on delete cascade,
  sender_id text not null,
  sender_role text not null check(sender_role in ('passenger','driver','admin','system')),
  message text not null,
  created_at timestamptz not null default now()
);
create index if not exists support_messages_case_idx on public.support_messages(case_id,created_at);

-- Regla central: una cuenta suspendida nunca puede permanecer en línea.
create or replace function public.enforce_profile_operability()
returns trigger
language plpgsql
set search_path=public
as $$
begin
  if new.suspended_until is not null and new.suspended_until>now() then
    new.is_online:=false;
  end if;
  if new.approval_status in ('deleted','rejected') or new.status in ('deleted','blocked') then
    new.is_online:=false;
  end if;
  return new;
end;
$$;
drop trigger if exists profiles_enforce_operability on public.profiles;
create trigger profiles_enforce_operability before insert or update on public.profiles
for each row execute function public.enforce_profile_operability();

update public.profiles
set is_online=false,updated_at=now()
where (suspended_until is not null and suspended_until>now())
   or approval_status in ('deleted','rejected')
   or status in ('deleted','blocked');

-- Ofertas iniciales: excluye conductores suspendidos o bloqueados.
create or replace function public.assign_initial_driver_offer()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare v_driver text;
begin
  if new.status='searching' and new.offered_driver_id is null and new.pickup_lat is not null and new.pickup_lng is not null then
    select p.device_id into v_driver
    from public.profiles p
    where p.role='driver'
      and p.status='active'
      and p.approval_status='approved'
      and (p.suspended_until is null or p.suspended_until<=now())
      and coalesce(p.is_online,false)=true
      and p.last_lat is not null and p.last_lng is not null
      and (p.last_seen_at is null or p.last_seen_at>now()-interval '2 minutes')
      and (new.vehicle_type is null or p.vehicle_type is null or p.vehicle_type=new.vehicle_type)
      and not exists(select 1 from public.rides busy where busy.driver_id=p.device_id and busy.status in ('accepted','arrived','in_progress'))
    order by power(p.last_lat-new.pickup_lat,2)+power(p.last_lng-new.pickup_lng,2)
    limit 1;
    if v_driver is not null then
      new.offered_driver_id:=v_driver;
      new.offered_at:=now();
      new.offer_expires_at:=now()+interval '35 seconds';
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists rides_assign_initial_offer on public.rides;
create trigger rides_assign_initial_offer before insert on public.rides
for each row execute function public.assign_initial_driver_offer();

create or replace function public.claim_nearest_ride_offer(
  p_driver_id text,
  p_driver_lat double precision,
  p_driver_lng double precision,
  p_vehicle_type text default null
)
returns public.rides
language plpgsql
security definer
set search_path=public
as $$
declare v_id text;v_ride public.rides;
begin
  if not exists(
    select 1 from public.profiles p
    where p.device_id=p_driver_id
      and p.role='driver'
      and p.status='active'
      and p.approval_status='approved'
      and (p.suspended_until is null or p.suspended_until<=now())
      and coalesce(p.is_online,false)=true
  ) then return null; end if;

  if exists(select 1 from public.rides busy where busy.driver_id=p_driver_id and busy.status in ('accepted','arrived','in_progress')) then
    return null;
  end if;

  select r.id::text into v_id
  from public.rides r
  where r.status='searching'
    and (p_vehicle_type is null or r.vehicle_type is null or r.vehicle_type=p_vehicle_type)
    and (r.offered_driver_id=p_driver_id or r.offered_driver_id is null or r.offer_expires_at<now())
    and not exists(select 1 from public.ride_offer_attempts a where a.ride_id=r.id::text and a.driver_id=p_driver_id)
  order by case when r.pickup_lat is null or r.pickup_lng is null then 999999 else power(r.pickup_lat-p_driver_lat,2)+power(r.pickup_lng-p_driver_lng,2) end,r.created_at
  for update skip locked
  limit 1;

  if v_id is null then return null; end if;
  update public.rides
  set offered_driver_id=p_driver_id,offered_at=now(),offer_expires_at=now()+interval '35 seconds',updated_at=now()
  where id::text=v_id and status='searching'
  returning * into v_ride;
  return v_ride;
end;
$$;

create or replace function public.accept_ride_atomic(
  p_ride_id text,
  p_driver_id text,
  p_driver_name text,
  p_driver_photo text default null,
  p_driver_rating numeric default 5,
  p_driver_lat double precision default null,
  p_driver_lng double precision default null
)
returns public.rides
language plpgsql
security definer
set search_path=public
as $$
declare v_ride public.rides;
begin
  update public.rides
  set status='accepted',driver_id=p_driver_id,driver_name=p_driver_name,
      driver_photo=p_driver_photo,driver_rating=coalesce(p_driver_rating,5),
      driver_lat=p_driver_lat,driver_lng=p_driver_lng,accepted_at=now(),
      driver_last_update_at=now(),offered_driver_id=null,offered_at=null,
      offer_expires_at=null,last_event_at=now(),updated_at=now()
  where id::text=p_ride_id and status='searching'
    and (offered_driver_id is null or offered_driver_id=p_driver_id or offer_expires_at<now())
    and exists(
      select 1 from public.profiles p
      where p.device_id=p_driver_id and p.role='driver' and p.status='active'
        and p.approval_status='approved'
        and (p.suspended_until is null or p.suspended_until<=now())
        and coalesce(p.is_online,false)=true
    )
    and not exists(
      select 1 from public.rides busy
      where busy.driver_id=p_driver_id and busy.status in ('accepted','arrived','in_progress') and busy.id::text<>p_ride_id
    )
  returning * into v_ride;

  if not found then
    raise exception using errcode='P0001',message='RIDE_UNAVAILABLE_OR_DRIVER_BLOCKED';
  end if;

  begin
    insert into public.ride_events(ride_id,event_type,actor_role,actor_id,metadata)
    values(p_ride_id,'accepted','driver',p_driver_id,jsonb_build_object('driver_name',p_driver_name));
  exception when others then null;
  end;
  return v_ride;
end;
$$;

-- Administración atómica de viajes atascados.
create or replace function public.admin_resolve_ride(
  p_ride_id text,
  p_action text,
  p_reason text,
  p_admin_name text,
  p_admin_code text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v_ride public.rides;v_now timestamptz:=now();
begin
  if p_admin_code is distinct from 'RUEDA2026' then
    raise exception using errcode='P0001',message='ADMIN_CODE_INVALID';
  end if;
  if p_action not in ('finish','cancel') then
    raise exception using errcode='P0001',message='ADMIN_RIDE_ACTION_INVALID';
  end if;
  if nullif(trim(coalesce(p_reason,'')),'') is null then
    raise exception using errcode='P0001',message='ADMIN_RIDE_REASON_REQUIRED';
  end if;

  select * into v_ride from public.rides where id::text=p_ride_id for update;
  if not found then raise exception using errcode='P0001',message='RIDE_NOT_FOUND'; end if;

  if p_action='finish' then
    if v_ride.status not in ('accepted','arrived','in_progress') then
      raise exception using errcode='P0001',message='RIDE_CANNOT_BE_FINISHED_FROM_CURRENT_STATUS';
    end if;
    update public.rides
    set status='finished',finished_at=v_now,admin_finished_at=v_now,
        admin_finished_by=coalesce(nullif(trim(p_admin_name),''),'administración'),
        admin_note=trim(p_reason),offered_driver_id=null,offer_expires_at=null,
        last_event_at=v_now,updated_at=v_now
    where id::text=p_ride_id returning * into v_ride;
  else
    if v_ride.status not in ('searching','accepted','arrived','in_progress') then
      raise exception using errcode='P0001',message='RIDE_CANNOT_BE_CANCELED_FROM_CURRENT_STATUS';
    end if;
    update public.rides
    set status='canceled',canceled_at=v_now,canceled_by='admin',cancel_reason=trim(p_reason),
        admin_note=trim(p_reason),offered_driver_id=null,offered_at=null,offer_expires_at=null,
        last_event_at=v_now,updated_at=v_now
    where id::text=p_ride_id returning * into v_ride;
  end if;

  begin
    insert into public.ride_events(ride_id,event_type,actor_role,actor_id,metadata)
    values(p_ride_id,'admin_'||p_action,'admin',p_admin_name,jsonb_build_object('reason',trim(p_reason),'status',v_ride.status));
  exception when undefined_table or undefined_column then null;
  end;
  begin
    insert into public.admin_action_log(action,target_id,target_role,reason,admin_name,metadata,created_at)
    values('admin_'||p_action||'_ride',p_ride_id,'ride',trim(p_reason),p_admin_name,jsonb_build_object('final_status',v_ride.status),v_now);
  exception when undefined_table or undefined_column then null;
  end;

  return jsonb_build_object('ok',true,'ride_id',p_ride_id,'status',v_ride.status);
end;
$$;

-- Suspensión robusta de pasajero o conductor.
create or replace function public.admin_suspend_profile(
  p_person_id text,p_role text,p_until timestamptz,p_reason text,p_admin_name text,p_admin_code text
)
returns public.profiles
language plpgsql
security definer
set search_path=public
as $$
declare v_profile public.profiles;
begin
  if p_admin_code is distinct from 'RUEDA2026' then raise exception using errcode='P0001',message='ADMIN_CODE_INVALID'; end if;
  if p_until is null or p_until<=now() then raise exception using errcode='P0001',message='SUSPENSION_DATE_INVALID'; end if;
  if nullif(trim(coalesce(p_reason,'')),'') is null then raise exception using errcode='P0001',message='SUSPENSION_REASON_REQUIRED'; end if;

  select * into v_profile from public.profiles p
  where p.role=p_role and (p.device_id=p_person_id or p.id::text=p_person_id)
  limit 1 for update;
  if not found then raise exception using errcode='P0001',message='PROFILE_NOT_FOUND'; end if;

  update public.profiles set suspended_until=p_until,suspension_reason=trim(p_reason),suspended_at=now(),
    suspended_by=coalesce(nullif(trim(p_admin_name),''),'administración'),is_online=false,updated_at=now()
  where id=v_profile.id returning * into v_profile;

  update public.rides
  set status='canceled',canceled_at=now(),canceled_by='admin',cancel_reason='Cuenta suspendida: '||trim(p_reason),
      admin_note='Suspensión administrativa hasta '||p_until::text,offered_driver_id=null,offered_at=null,offer_expires_at=null,
      updated_at=now(),last_event_at=now()
  where status in ('searching','accepted','arrived','in_progress') and (
    (p_role='driver' and driver_id in (coalesce(v_profile.device_id,''),v_profile.id::text,p_person_id)) or
    (p_role='passenger' and passenger_id in (coalesce(v_profile.device_id,''),v_profile.id::text,p_person_id))
  );

  begin
    insert into public.admin_action_log(action,target_id,target_role,reason,admin_name,metadata,created_at)
    values('suspend_'||p_role,coalesce(v_profile.device_id,v_profile.id::text),p_role,trim(p_reason),p_admin_name,jsonb_build_object('suspended_until',p_until),now());
  exception when undefined_table or undefined_column then null;
  end;
  return v_profile;
end;
$$;

create or replace function public.admin_unsuspend_profile(
  p_person_id text,p_role text,p_admin_name text,p_admin_code text
)
returns public.profiles
language plpgsql
security definer
set search_path=public
as $$
declare v_profile public.profiles;
begin
  if p_admin_code is distinct from 'RUEDA2026' then raise exception using errcode='P0001',message='ADMIN_CODE_INVALID'; end if;
  update public.profiles p set suspended_until=null,suspension_reason=null,suspended_at=null,suspended_by=null,updated_at=now()
  where p.role=p_role and (p.device_id=p_person_id or p.id::text=p_person_id)
  returning * into v_profile;
  if not found then raise exception using errcode='P0001',message='PROFILE_NOT_FOUND'; end if;
  begin
    insert into public.admin_action_log(action,target_id,target_role,reason,admin_name,metadata,created_at)
    values('unsuspend_'||p_role,coalesce(v_profile.device_id,v_profile.id::text),p_role,'Suspensión levantada manualmente',p_admin_name,'{}'::jsonb,now());
  exception when undefined_table or undefined_column then null;
  end;
  return v_profile;
end;
$$;

-- Eliminación definitiva tolerante a diferencias de esquema entre versiones anteriores.
create or replace function public.admin_delete_person_permanently(
  p_person_id text,p_role text,p_reason text,p_admin_name text,p_admin_code text
)
returns jsonb
language plpgsql
security definer
set search_path=public,storage
as $$
declare
  v_profile public.profiles;
  v_keys text[];
  v_ride_ids text[]:=array[]::text[];
  v_rides_count integer:=0;
  v_media_count integer:=0;
  v_sql text;
begin
  if p_admin_code is distinct from 'RUEDA2026' then raise exception using errcode='P0001',message='ADMIN_CODE_INVALID'; end if;
  if nullif(trim(coalesce(p_reason,'')),'') is null then raise exception using errcode='P0001',message='DELETE_REASON_REQUIRED'; end if;
  if p_role not in ('driver','passenger') then raise exception using errcode='P0001',message='ROLE_INVALID'; end if;

  select * into v_profile from public.profiles p
  where p.role=p_role and (p.device_id=p_person_id or p.id::text=p_person_id)
  limit 1 for update;
  if not found then raise exception using errcode='P0001',message='PROFILE_NOT_FOUND'; end if;

  v_keys:=array_remove(array[p_person_id,v_profile.id::text,v_profile.device_id],null);
  select coalesce(array_agg(id::text),array[]::text[]) into v_ride_ids
  from public.rides
  where (p_role='driver' and driver_id=any(v_keys)) or (p_role='passenger' and passenger_id=any(v_keys));
  v_rides_count:=coalesce(array_length(v_ride_ids,1),0);

  if to_regclass('public.driver_reports') is not null then
    v_sql:='delete from public.driver_reports where false';
    if exists(select 1 from information_schema.columns where table_schema='public' and table_name='driver_reports' and column_name='ride_id') then
      v_sql:=v_sql||' or ride_id::text=any($1)';
    end if;
    if p_role='driver' and exists(select 1 from information_schema.columns where table_schema='public' and table_name='driver_reports' and column_name='driver_id') then
      v_sql:=v_sql||' or driver_id::text=any($2)';
    end if;
    if p_role='passenger' and exists(select 1 from information_schema.columns where table_schema='public' and table_name='driver_reports' and column_name='passenger_id') then
      v_sql:=v_sql||' or passenger_id::text=any($2)';
    end if;
    execute v_sql using v_ride_ids,v_keys;
  end if;

  if to_regclass('public.ride_events') is not null then execute 'delete from public.ride_events where ride_id::text=any($1)' using v_ride_ids; end if;
  if to_regclass('public.ride_offer_attempts') is not null then execute 'delete from public.ride_offer_attempts where ride_id::text=any($1) or driver_id::text=any($2)' using v_ride_ids,v_keys; end if;
  if to_regclass('public.ride_messages') is not null then execute 'delete from public.ride_messages where ride_id::text=any($1) or sender_id::text=any($2)' using v_ride_ids,v_keys; end if;

  if to_regclass('public.support_cases') is not null then
    delete from public.support_cases where created_by_id=any(v_keys) or related_ride_id=any(v_ride_ids);
  end if;

  delete from public.rides where id::text=any(v_ride_ids);

  begin
    with deleted as (
      delete from storage.objects
      where bucket_id='sobre-ruedas-media' and (
        name like '%/'||coalesce(v_profile.device_id,'__none__')||'/%' or
        name like '%/'||v_profile.id::text||'/%'
      ) returning 1
    ) select count(*) into v_media_count from deleted;
  exception when others then
    v_media_count:=0;
  end;

  delete from public.profiles where id=v_profile.id;

  begin
    execute 'delete from public.admin_action_log where target_id::text=any($1)' using v_keys;
    insert into public.admin_action_log(action,target_id,target_role,reason,admin_name,metadata,created_at)
    values('permanent_delete_'||p_role,'[eliminado]',p_role,trim(p_reason),p_admin_name,
      jsonb_build_object('rides_deleted',v_rides_count,'media_deleted',v_media_count),now());
  exception when others then null;
  end;

  return jsonb_build_object('ok',true,'role',p_role,'rides_deleted',v_rides_count,'media_deleted',v_media_count);
end;
$$;

-- Mensajería del viaje. La interfaz solo la habilita para participantes del viaje.
create or replace function public.send_ride_message(
  p_ride_id text,p_sender_id text,p_sender_role text,p_message text,p_message_type text default 'text'
)
returns public.ride_messages
language plpgsql
security definer
set search_path=public
as $$
declare v_ride public.rides;v_message public.ride_messages;
begin
  if p_sender_role not in ('passenger','driver') then raise exception using errcode='P0001',message='MESSAGE_ROLE_INVALID'; end if;
  if nullif(trim(coalesce(p_message,'')),'') is null then raise exception using errcode='P0001',message='MESSAGE_EMPTY'; end if;
  if length(p_message)>800 then raise exception using errcode='P0001',message='MESSAGE_TOO_LONG'; end if;
  select * into v_ride from public.rides where id::text=p_ride_id;
  if not found then raise exception using errcode='P0001',message='RIDE_NOT_FOUND'; end if;
  if not ((p_sender_role='passenger' and v_ride.passenger_id=p_sender_id) or (p_sender_role='driver' and v_ride.driver_id=p_sender_id)) then
    raise exception using errcode='P0001',message='MESSAGE_SENDER_NOT_PARTICIPANT';
  end if;
  if v_ride.status not in ('searching','accepted','arrived','in_progress') and coalesce(v_ride.finished_at,v_ride.canceled_at,v_ride.updated_at)<now()-interval '30 minutes' then
    raise exception using errcode='P0001',message='CHAT_CLOSED';
  end if;
  insert into public.ride_messages(ride_id,sender_id,sender_role,message,message_type)
  values(p_ride_id,p_sender_id,p_sender_role,trim(p_message),coalesce(nullif(p_message_type,''),'text'))
  returning * into v_message;
  return v_message;
end;
$$;

create or replace function public.mark_ride_messages_read(
  p_ride_id text,p_reader_id text,p_reader_role text
)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare v_count integer;v_ride public.rides;
begin
  select * into v_ride from public.rides where id::text=p_ride_id;
  if not found then return 0; end if;
  if not ((p_reader_role='passenger' and v_ride.passenger_id=p_reader_id) or (p_reader_role='driver' and v_ride.driver_id=p_reader_id)) then
    raise exception using errcode='P0001',message='MESSAGE_READER_NOT_PARTICIPANT';
  end if;
  update public.ride_messages set read_at=coalesce(read_at,now())
  where ride_id=p_ride_id and sender_id<>p_reader_id and read_at is null;
  get diagnostics v_count=row_count;
  return v_count;
end;
$$;

create or replace function public.create_support_case(
  p_creator_id text,p_creator_role text,p_ride_id text,p_category text,p_subject text,p_description text,p_priority text default 'normal'
)
returns public.support_cases
language plpgsql
security definer
set search_path=public
as $$
declare v_case public.support_cases;
begin
  if p_creator_role not in ('passenger','driver') then raise exception using errcode='P0001',message='SUPPORT_ROLE_INVALID'; end if;
  if nullif(trim(coalesce(p_category,'')),'') is null or nullif(trim(coalesce(p_description,'')),'') is null then
    raise exception using errcode='P0001',message='SUPPORT_DETAILS_REQUIRED';
  end if;
  insert into public.support_cases(created_by_id,created_by_role,related_ride_id,category,subject,description,priority)
  values(p_creator_id,p_creator_role,nullif(p_ride_id,''),trim(p_category),coalesce(nullif(trim(p_subject),''),trim(p_category)),trim(p_description),
    case when p_priority in ('normal','high','emergency') then p_priority else 'normal' end)
  returning * into v_case;
  if p_ride_id is not null and p_ride_id<>'' then update public.rides set support_flag=true,updated_at=now() where id::text=p_ride_id; end if;
  insert into public.support_messages(case_id,sender_id,sender_role,message)
  values(v_case.id,p_creator_id,p_creator_role,trim(p_description));
  return v_case;
end;
$$;


create or replace function public.send_support_message(
  p_case_id uuid,p_sender_id text,p_sender_role text,p_message text
)
returns public.support_messages
language plpgsql
security definer
set search_path=public
as $$
declare v_case public.support_cases;v_message public.support_messages;
begin
  if p_sender_role not in ('passenger','driver') then raise exception using errcode='P0001',message='SUPPORT_ROLE_INVALID'; end if;
  if nullif(trim(coalesce(p_message,'')),'') is null then raise exception using errcode='P0001',message='SUPPORT_MESSAGE_EMPTY'; end if;
  if length(p_message)>1800 then raise exception using errcode='P0001',message='SUPPORT_MESSAGE_TOO_LONG'; end if;
  select * into v_case from public.support_cases where id=p_case_id for update;
  if not found then raise exception using errcode='P0001',message='SUPPORT_CASE_NOT_FOUND'; end if;
  if v_case.created_by_id<>p_sender_id or v_case.created_by_role<>p_sender_role then
    raise exception using errcode='P0001',message='SUPPORT_SENDER_NOT_OWNER';
  end if;
  if v_case.status in ('resolved','closed') then raise exception using errcode='P0001',message='SUPPORT_CASE_CLOSED'; end if;
  insert into public.support_messages(case_id,sender_id,sender_role,message)
  values(p_case_id,p_sender_id,p_sender_role,trim(p_message)) returning * into v_message;
  update public.support_cases set status=case when status='open' then 'in_review' else status end,updated_at=now() where id=p_case_id;
  return v_message;
end;
$$;

grant execute on function public.claim_nearest_ride_offer(text,double precision,double precision,text) to anon,authenticated;
grant execute on function public.accept_ride_atomic(text,text,text,text,numeric,double precision,double precision) to anon,authenticated;
grant execute on function public.admin_resolve_ride(text,text,text,text,text) to anon,authenticated;
grant execute on function public.admin_suspend_profile(text,text,timestamptz,text,text,text) to anon,authenticated;
grant execute on function public.admin_unsuspend_profile(text,text,text,text) to anon,authenticated;
grant execute on function public.admin_delete_person_permanently(text,text,text,text,text) to anon,authenticated;
grant execute on function public.send_ride_message(text,text,text,text,text) to anon,authenticated;
grant execute on function public.mark_ride_messages_read(text,text,text) to anon,authenticated;
grant execute on function public.create_support_case(text,text,text,text,text,text,text) to anon,authenticated;
grant execute on function public.send_support_message(uuid,text,text,text) to anon,authenticated;

grant select,insert,update,delete on table public.ride_events to anon,authenticated;
grant select,insert,update,delete on table public.ride_offer_attempts to anon,authenticated;
grant select,update on table public.ride_messages to anon,authenticated;
grant select,insert,update on table public.support_cases to anon,authenticated;
grant select,insert on table public.support_messages to anon,authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;

alter table public.ride_messages enable row level security;
alter table public.support_cases enable row level security;
alter table public.support_messages enable row level security;

drop policy if exists beta_ride_messages_read on public.ride_messages;
create policy beta_ride_messages_read on public.ride_messages for select to anon,authenticated using(true);
drop policy if exists beta_support_cases on public.support_cases;
create policy beta_support_cases on public.support_cases for all to anon,authenticated using(true) with check(true);
drop policy if exists beta_support_messages on public.support_messages;
create policy beta_support_messages on public.support_messages for all to anon,authenticated using(true) with check(true);

do $$ begin alter publication supabase_realtime add table public.ride_messages; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.support_cases; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.support_messages; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.rides; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.profiles; exception when duplicate_object then null; end $$;
alter table public.ride_messages replica identity full;
alter table public.support_cases replica identity full;
alter table public.support_messages replica identity full;
alter table public.rides replica identity full;
alter table public.profiles replica identity full;

notify pgrst,'reload schema';
commit;
