-- SOBRE RUEDAS v2.4.0
-- Centro de control administrativo: estados de conductores y resolución de reportes.
-- Seguro para ejecutar más de una vez.

begin;

-- Estados administrativos del perfil.
create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid()
);
alter table public.profiles add column if not exists role text default 'passenger';
alter table public.profiles add column if not exists status text default 'pending';
alter table public.profiles add column if not exists approved_at timestamptz;
alter table public.profiles add column if not exists approved_by text;
alter table public.profiles add column if not exists suspended_at timestamptz;
alter table public.profiles add column if not exists suspended_by text;
alter table public.profiles add column if not exists rejection_reason text;
alter table public.profiles add column if not exists updated_at timestamptz default now();

update public.profiles
set status=case
  when status is null or btrim(status)='' then 'pending'
  when lower(status) in ('approved','aprobado') then 'active'
  when lower(status) in ('blocked','bloqueado') then 'suspended'
  when lower(status) in ('denied','rechazado','desaprobado') then 'rejected'
  else lower(status)
end;

alter table public.profiles drop constraint if exists profiles_status_check;
alter table public.profiles add constraint profiles_status_check
check (status in ('pending','active','suspended','rejected')) not valid;

create index if not exists profiles_role_status_idx on public.profiles(role,status);

-- Acciones de solución, eliminación lógica y restauración de reportes.
create table if not exists public.driver_reports (
  id uuid primary key default gen_random_uuid()
);
alter table public.driver_reports add column if not exists reviewed boolean default false;
alter table public.driver_reports add column if not exists reviewed_at timestamptz;
alter table public.driver_reports add column if not exists reviewed_by text;
alter table public.driver_reports add column if not exists resolution_notes text;
alter table public.driver_reports add column if not exists dismissed boolean default false;
alter table public.driver_reports add column if not exists dismissed_at timestamptz;
alter table public.driver_reports add column if not exists dismissed_by text;
alter table public.driver_reports add column if not exists updated_at timestamptz default now();

update public.driver_reports set reviewed=false where reviewed is null;
update public.driver_reports set dismissed=false where dismissed is null;
create index if not exists driver_reports_admin_state_idx
on public.driver_reports(dismissed,reviewed,created_at desc);

-- Registro auditable de decisiones administrativas.
create table if not exists public.admin_actions (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text,
  action text not null,
  performed_by text,
  details jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);
create index if not exists admin_actions_entity_idx
on public.admin_actions(entity_type,entity_id,created_at desc);

-- Permisos de beta necesarios para que el panel pueda administrar.
grant select,insert,update,delete on table public.profiles to anon,authenticated;
grant select,insert,update,delete on table public.driver_reports to anon,authenticated;
grant select,insert on table public.admin_actions to anon,authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;

alter table public.profiles enable row level security;
alter table public.driver_reports enable row level security;
alter table public.admin_actions enable row level security;

drop policy if exists beta_profiles on public.profiles;
create policy beta_profiles on public.profiles for all to anon,authenticated using(true) with check(true);

drop policy if exists beta_driver_reports on public.driver_reports;
create policy beta_driver_reports on public.driver_reports for all to anon,authenticated using(true) with check(true);

drop policy if exists beta_admin_actions on public.admin_actions;
create policy beta_admin_actions on public.admin_actions for all to anon,authenticated using(true) with check(true);

commit;
