-- Sobre Ruedas v2.4.1 · Mapa operativo en vivo y sincronización de usuarios/conductores
-- Migración segura e idempotente desde v2.4.0.
-- No borra viajes, usuarios, conductores, reportes ni tarifas existentes.

begin;

create extension if not exists pgcrypto;

do $$
begin
  if to_regclass('public.rides') is null then
    raise exception 'No existe public.rides. Ejecuta primero ACTUALIZAR_SUPABASE_v2.4.0.sql.';
  end if;
  if to_regclass('public.profiles') is null then
    raise exception 'No existe public.profiles. Ejecuta primero ACTUALIZAR_SUPABASE_v2.4.0.sql.';
  end if;
end
$$;

-- Coordenadas necesarias para el mapa operativo normal de OpenStreetMap.
alter table public.rides add column if not exists pickup_lat double precision;
alter table public.rides add column if not exists pickup_lng double precision;
alter table public.rides add column if not exists destination_lat double precision;
alter table public.rides add column if not exists destination_lng double precision;
alter table public.rides add column if not exists distance_km numeric;
alter table public.rides add column if not exists updated_at timestamptz default now();

create index if not exists rides_live_status_idx
  on public.rides(status,updated_at desc);
create index if not exists rides_driver_live_idx
  on public.rides(driver_id,status,updated_at desc);

-- Motivos y auditoría del control administrativo.
alter table public.profiles add column if not exists rejection_reason text;
alter table public.profiles add column if not exists deleted_reason text;
alter table public.profiles add column if not exists deleted_by text;
alter table public.profiles add column if not exists deleted_at timestamptz;
alter table public.profiles add column if not exists last_lat double precision;
alter table public.profiles add column if not exists last_lng double precision;
alter table public.profiles add column if not exists last_seen_at timestamptz;
alter table public.profiles add column if not exists is_online boolean default false;
alter table public.profiles add column if not exists updated_at timestamptz default now();

update public.profiles
set is_online=false
where is_online is null;

create index if not exists profiles_admin_list_idx
  on public.profiles(role,status,approval_status,updated_at desc);
create index if not exists profiles_live_map_idx
  on public.profiles(role,is_online,last_seen_at desc)
  where role='driver';

create table if not exists public.admin_action_log (
  id bigint generated by default as identity primary key,
  action text not null,
  target_id text not null,
  target_role text,
  reason text,
  admin_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_action_log_target_idx
  on public.admin_action_log(target_role,target_id,created_at desc);
create index if not exists admin_action_log_created_idx
  on public.admin_action_log(created_at desc);

-- Los datos antiguos quedan visibles en las nuevas páginas administrativas.
update public.profiles
set approval_status=case
      when status='deleted' then 'deleted'
      when role='driver' and status='blocked' then 'rejected'
      when role='driver' and approval_status is null then 'pending'
      when role<>'driver' and approval_status is null then 'approved'
      else approval_status
    end,
    updated_at=coalesce(updated_at,now());

-- Permisos de la beta web. El historial se conserva; la eliminación es lógica.
grant select,insert,update on table public.rides to anon,authenticated;
grant select,insert,update,delete on table public.profiles to anon,authenticated;
grant select,insert on table public.admin_action_log to anon,authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;

alter table public.rides enable row level security;
alter table public.profiles enable row level security;
alter table public.admin_action_log enable row level security;

-- Mantiene compatibilidad si las políticas v2.4.0 ya existen.
drop policy if exists beta_admin_action_log_read on public.admin_action_log;
drop policy if exists beta_admin_action_log_insert on public.admin_action_log;
create policy beta_admin_action_log_read
  on public.admin_action_log for select to anon,authenticated using(true);
create policy beta_admin_action_log_insert
  on public.admin_action_log for insert to anon,authenticated with check(true);

-- Realtime para viajes y perfiles. Los bloques son idempotentes.
do $$
begin
  alter publication supabase_realtime add table public.rides;
exception when duplicate_object then null;
end
$$;

do $$
begin
  alter publication supabase_realtime add table public.profiles;
exception when duplicate_object then null;
end
$$;

-- Permite que los UPDATE de Realtime incluyan la fila completa.
alter table public.rides replica identity full;
alter table public.profiles replica identity full;

notify pgrst,'reload schema';

commit;
