-- Sobre Ruedas v2.4.3 · Corrección de eliminación lógica
-- Migración segura e idempotente desde v2.4.2.
-- No borra viajes, usuarios, conductores, reportes ni tarifas.

begin;

create extension if not exists pgcrypto;

do $$
begin
  if to_regclass('public.profiles') is null then
    raise exception 'No existe public.profiles. Ejecuta primero ACTUALIZAR_SUPABASE_v2.4.2.sql.';
  end if;
end
$$;

-- Columnas utilizadas por la eliminación lógica y su restauración.
alter table public.profiles add column if not exists approval_status text default 'pending';
alter table public.profiles add column if not exists is_online boolean default false;
alter table public.profiles add column if not exists deleted_at timestamptz;
alter table public.profiles add column if not exists deleted_reason text;
alter table public.profiles add column if not exists deleted_by text;
alter table public.profiles add column if not exists updated_at timestamptz default now();

-- La beta usa identidad local por device_id. Se conservan los permisos de operación actuales.
grant select,insert,update,delete on table public.profiles to anon,authenticated;
alter table public.profiles enable row level security;
drop policy if exists beta_profiles on public.profiles;
create policy beta_profiles
  on public.profiles
  for all
  to anon,authenticated
  using(true)
  with check(true);

-- Normaliza perfiles que versiones anteriores marcaron parcialmente como eliminados.
update public.profiles
set approval_status='deleted',
    is_online=false,
    updated_at=coalesce(updated_at,now())
where status='deleted'
  and approval_status is distinct from 'deleted';

-- Auditoría administrativa, si aún no existe.
create table if not exists public.admin_action_log (
  id bigint generated by default as identity primary key,
  action text not null,
  target_id text not null,
  target_role text,
  reason text,
  admin_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
grant select,insert on table public.admin_action_log to anon,authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;
alter table public.admin_action_log enable row level security;
drop policy if exists beta_admin_action_log_read on public.admin_action_log;
drop policy if exists beta_admin_action_log_insert on public.admin_action_log;
create policy beta_admin_action_log_read on public.admin_action_log for select to anon,authenticated using(true);
create policy beta_admin_action_log_insert on public.admin_action_log for insert to anon,authenticated with check(true);

alter table public.profiles replica identity full;
notify pgrst,'reload schema';

commit;
