-- Sobre Ruedas v2.5.0 · Flujo profesional, paneles separados y navegación
-- Migración segura e idempotente desde v2.4.3. No elimina información existente.

begin;
create extension if not exists pgcrypto;

do $$ begin
  if to_regclass('public.rides') is null or to_regclass('public.profiles') is null then
    raise exception 'Faltan las tablas base. Actualiza primero hasta Sobre Ruedas v2.4.3.';
  end if;
end $$;

-- Coordenadas, tiempos y auditoría del flujo profesional.
alter table public.rides add column if not exists pickup_lat double precision;
alter table public.rides add column if not exists pickup_lng double precision;
alter table public.rides add column if not exists destination_lat double precision;
alter table public.rides add column if not exists destination_lng double precision;
alter table public.rides add column if not exists distance_km numeric default 0;
alter table public.rides add column if not exists eta_minutes integer;
alter table public.rides add column if not exists trip_code text;
alter table public.rides add column if not exists driver_last_update_at timestamptz;
alter table public.rides add column if not exists last_event_at timestamptz default now();
alter table public.rides add column if not exists client_version text;
alter table public.rides add column if not exists driver_version text;
alter table public.rides add column if not exists cancel_reason text;
alter table public.rides add column if not exists admin_note text;
alter table public.rides add column if not exists offered_driver_id text;
alter table public.rides add column if not exists offer_expires_at timestamptz;
alter table public.rides add column if not exists offered_at timestamptz;

alter table public.profiles add column if not exists app_version text;
alter table public.profiles add column if not exists last_lat double precision;
alter table public.profiles add column if not exists last_lng double precision;
alter table public.profiles add column if not exists last_seen_at timestamptz;
alter table public.profiles add column if not exists is_online boolean default false;

create index if not exists rides_live_operations_idx on public.rides(status,updated_at desc);
create index if not exists rides_searching_created_idx on public.rides(created_at) where status='searching';
create index if not exists rides_driver_live_idx on public.rides(driver_id,status,updated_at desc);
create index if not exists rides_passenger_live_idx on public.rides(passenger_id,status,updated_at desc);
create index if not exists rides_offer_idx on public.rides(status,offered_driver_id,offer_expires_at) where status='searching';

create table if not exists public.ride_events (
  id bigint generated by default as identity primary key,
  ride_id text,
  event_type text not null,
  actor_role text,
  actor_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists ride_events_ride_idx on public.ride_events(ride_id,created_at desc);



create table if not exists public.ride_offer_attempts (
  id bigint generated by default as identity primary key,
  ride_id text not null,
  driver_id text not null,
  outcome text not null default 'declined',
  created_at timestamptz not null default now()
);
create index if not exists ride_offer_attempts_lookup_idx on public.ride_offer_attempts(ride_id,driver_id,created_at desc);

-- En la creación se ofrece primero al conductor aprobado y conectado más cercano.
create or replace function public.assign_initial_driver_offer()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare v_driver text;
begin
  if new.status='searching' and new.offered_driver_id is null and new.pickup_lat is not null and new.pickup_lng is not null then
    select p.device_id into v_driver
    from public.profiles p
    where p.role='driver' and p.status='active' and p.approval_status='approved'
      and coalesce(p.is_online,false)=true and p.last_lat is not null and p.last_lng is not null
      and (p.last_seen_at is null or p.last_seen_at>now()-interval '2 minutes')
      and (new.vehicle_type is null or p.vehicle_type is null or p.vehicle_type=new.vehicle_type)
      and not exists(select 1 from public.rides busy where busy.driver_id=p.device_id and busy.status in ('accepted','arrived','in_progress'))
    order by power(p.last_lat-new.pickup_lat,2)+power(p.last_lng-new.pickup_lng,2)
    limit 1;
    if v_driver is not null then new.offered_driver_id=v_driver;new.offered_at=now();new.offer_expires_at=now()+interval '35 seconds';end if;
  end if;
  return new;
end;
$$;
drop trigger if exists rides_assign_initial_offer on public.rides;
create trigger rides_assign_initial_offer before insert on public.rides for each row execute function public.assign_initial_driver_offer();

-- Un conductor libre reclama atómicamente la solicitud disponible más cercana.
create or replace function public.claim_nearest_ride_offer(p_driver_id text,p_driver_lat double precision,p_driver_lng double precision,p_vehicle_type text default null)
returns public.rides
language plpgsql
security definer
set search_path=public
as $$
declare v_id text;v_ride public.rides;
begin
  if not exists(
    select 1 from public.profiles p
    where p.device_id=p_driver_id and p.role='driver' and p.status='active'
      and p.approval_status='approved' and coalesce(p.is_online,false)=true
  ) then return null; end if;
  if exists(select 1 from public.rides busy where busy.driver_id=p_driver_id and busy.status in ('accepted','arrived','in_progress')) then return null; end if;
  select r.id::text into v_id
  from public.rides r
  where r.status='searching'
    and (p_vehicle_type is null or r.vehicle_type is null or r.vehicle_type=p_vehicle_type)
    and (r.offered_driver_id=p_driver_id or r.offered_driver_id is null or r.offer_expires_at<now())
    and not exists(select 1 from public.ride_offer_attempts a where a.ride_id=r.id::text and a.driver_id=p_driver_id)
  order by case when r.pickup_lat is null or r.pickup_lng is null then 999999 else power(r.pickup_lat-p_driver_lat,2)+power(r.pickup_lng-p_driver_lng,2) end,r.created_at
  for update skip locked
  limit 1;
  if v_id is null then return null;end if;
  update public.rides set offered_driver_id=p_driver_id,offered_at=now(),offer_expires_at=now()+interval '35 seconds',updated_at=now() where id::text=v_id and status='searching' returning * into v_ride;
  return v_ride;
end;
$$;

-- Al rechazar o vencer la oferta, la pasa al siguiente conductor cercano.
create or replace function public.decline_ride_offer(p_ride_id text,p_driver_id text,p_outcome text default 'declined')
returns public.rides
language plpgsql
security definer
set search_path=public
as $$
declare v_ride public.rides;v_next text;
begin
  insert into public.ride_offer_attempts(ride_id,driver_id,outcome) values(p_ride_id,p_driver_id,coalesce(p_outcome,'declined'));
  select * into v_ride from public.rides where id::text=p_ride_id and status='searching' and (offered_driver_id is null or offered_driver_id=p_driver_id or offer_expires_at<now()) for update;
  if not found then return null;end if;
  select p.device_id into v_next from public.profiles p
  where p.role='driver' and p.status='active' and p.approval_status='approved' and coalesce(p.is_online,false)=true
    and p.last_lat is not null and p.last_lng is not null and p.device_id<>p_driver_id
    and (p.last_seen_at is null or p.last_seen_at>now()-interval '2 minutes')
    and (v_ride.vehicle_type is null or p.vehicle_type is null or p.vehicle_type=v_ride.vehicle_type)
    and not exists(select 1 from public.ride_offer_attempts a where a.ride_id=p_ride_id and a.driver_id=p.device_id)
    and not exists(select 1 from public.rides busy where busy.driver_id=p.device_id and busy.status in ('accepted','arrived','in_progress'))
  order by case when v_ride.pickup_lat is null or v_ride.pickup_lng is null then 999999 else power(p.last_lat-v_ride.pickup_lat,2)+power(p.last_lng-v_ride.pickup_lng,2) end
  limit 1;
  update public.rides set offered_driver_id=v_next,offered_at=case when v_next is null then null else now() end,offer_expires_at=case when v_next is null then null else now()+interval '35 seconds' end,updated_at=now() where id::text=p_ride_id returning * into v_ride;
  return v_ride;
end;
$$;

grant execute on function public.claim_nearest_ride_offer(text,double precision,double precision,text) to anon,authenticated;
grant execute on function public.decline_ride_offer(text,text,text) to anon,authenticated;
grant select,insert on table public.ride_offer_attempts to anon,authenticated;

-- Aceptación atómica: impide que dos conductores tomen el mismo viaje.
create or replace function public.accept_ride_atomic(
  p_ride_id text,
  p_driver_id text,
  p_driver_name text,
  p_driver_photo text default null,
  p_driver_rating numeric default 5,
  p_driver_lat double precision default null,
  p_driver_lng double precision default null
)
returns public.rides
language plpgsql
security definer
set search_path=public
as $$
declare
  v_ride public.rides;
begin
  update public.rides
  set status='accepted',
      driver_id=p_driver_id,
      driver_name=p_driver_name,
      driver_photo=p_driver_photo,
      driver_rating=coalesce(p_driver_rating,5),
      driver_lat=p_driver_lat,
      driver_lng=p_driver_lng,
      accepted_at=now(),
      driver_last_update_at=now(),
      offered_driver_id=null,offered_at=null,offer_expires_at=null,
      last_event_at=now(),
      updated_at=now()
  where id::text=p_ride_id and status='searching'
    and (offered_driver_id is null or offered_driver_id=p_driver_id or offer_expires_at<now())
    and exists(select 1 from public.profiles p where p.device_id=p_driver_id and p.role='driver' and p.status='active' and p.approval_status='approved' and coalesce(p.is_online,false)=true)
    and not exists(select 1 from public.rides busy where busy.driver_id=p_driver_id and busy.status in ('accepted','arrived','in_progress') and busy.id::text<>p_ride_id)
  returning * into v_ride;

  if not found then
    raise exception using errcode='P0001', message='RIDE_UNAVAILABLE';
  end if;

  insert into public.ride_events(ride_id,event_type,actor_role,actor_id,metadata)
  values(p_ride_id,'accepted','driver',p_driver_id,jsonb_build_object('driver_name',p_driver_name));
  return v_ride;
end;
$$;

grant execute on function public.accept_ride_atomic(text,text,text,text,numeric,double precision,double precision) to anon,authenticated;

-- Registro automático de cada cambio de estado.
create or replace function public.audit_ride_status_change()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if tg_op='INSERT' then
    insert into public.ride_events(ride_id,event_type,actor_role,actor_id,metadata)
    values(new.id::text,'created','passenger',new.passenger_id,jsonb_build_object('status',new.status));
  elsif old.status is distinct from new.status then
    new.last_event_at=now();
    insert into public.ride_events(ride_id,event_type,actor_role,actor_id,metadata)
    values(new.id::text,'status_changed',coalesce(new.canceled_by,case when new.driver_id is not null then 'driver' else 'system' end),coalesce(new.driver_id,new.passenger_id),jsonb_build_object('from',old.status,'to',new.status));
  end if;
  if tg_op='INSERT' then new.last_event_at=coalesce(new.last_event_at,now());end if;
  return new;
end;
$$;

drop trigger if exists rides_audit_status on public.rides;
create trigger rides_audit_status before insert or update on public.rides for each row execute function public.audit_ride_status_change();

-- La beta continúa usando identidad local por dispositivo.
grant select,insert,update on table public.rides to anon,authenticated;
grant select,insert on table public.ride_events to anon,authenticated;
grant select,insert,update,delete on table public.profiles to anon,authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;

alter table public.rides enable row level security;
alter table public.ride_events enable row level security;
alter table public.ride_offer_attempts enable row level security;
alter table public.profiles enable row level security;

drop policy if exists beta_rides on public.rides;
create policy beta_rides on public.rides for all to anon,authenticated using(true) with check(true);
drop policy if exists beta_ride_events_read on public.ride_events;
drop policy if exists beta_ride_events_insert on public.ride_events;
create policy beta_ride_events_read on public.ride_events for select to anon,authenticated using(true);
create policy beta_ride_events_insert on public.ride_events for insert to anon,authenticated with check(true);
drop policy if exists beta_ride_offer_attempts_read on public.ride_offer_attempts;
drop policy if exists beta_ride_offer_attempts_insert on public.ride_offer_attempts;
create policy beta_ride_offer_attempts_read on public.ride_offer_attempts for select to anon,authenticated using(true);
create policy beta_ride_offer_attempts_insert on public.ride_offer_attempts for insert to anon,authenticated with check(true);
drop policy if exists beta_profiles on public.profiles;
create policy beta_profiles on public.profiles for all to anon,authenticated using(true) with check(true);

do $$ begin alter publication supabase_realtime add table public.rides; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.profiles; exception when duplicate_object then null; end $$;
alter table public.rides replica identity full;
alter table public.profiles replica identity full;
notify pgrst,'reload schema';
commit;
