-- SOBRE RUEDAS · PANEL ADMIN BETA
-- Ejecutar en Supabase > SQL Editor.

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(), device_id text unique,
  role text not null check (role in ('passenger','driver','admin','owner')),
  full_name text, phone text, email text, photo_url text, status text default 'active',
  vehicle_type text, vehicle_plate text, rating numeric default 5,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(), profile_id uuid references public.profiles(id) on delete cascade,
  admin_role text not null default 'supervisor' check (admin_role in ('owner','supervisor','support','driver_reviewer','accounting')),
  active boolean default true, created_at timestamptz default now()
);

create table if not exists public.fare_settings (
  vehicle_type text primary key, base_fare numeric not null default 0,
  per_km numeric not null default 0, minimum_fare numeric not null default 0,
  active boolean default true, updated_at timestamptz default now()
);

insert into public.fare_settings(vehicle_type,base_fare,per_km,minimum_fare) values
 ('Motorina',90,38,140),('Moto',110,45,170),('Bicitaxi',70,28,110),('Triciclo',120,48,190)
on conflict(vehicle_type) do nothing;

create table if not exists public.ride_events (
  id bigint generated by default as identity primary key,
  ride_id uuid references public.rides(id) on delete cascade,
  event_type text not null, actor_role text, actor_id text,
  metadata jsonb default '{}'::jsonb, created_at timestamptz default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  ride_id uuid references public.rides(id) on delete set null,
  reporter_id text, reporter_role text, category text, description text,
  status text default 'open', assigned_admin uuid references public.admin_users(id),
  resolution_notes text, created_at timestamptz default now(), resolved_at timestamptz
);

-- Permisos temporales SOLO para la beta actual.
grant select,insert,update on public.profiles,public.fare_settings,public.ride_events,public.reports to anon,authenticated;
grant select on public.admin_users to anon,authenticated;
alter table public.profiles enable row level security;
alter table public.admin_users enable row level security;
alter table public.fare_settings enable row level security;
alter table public.ride_events enable row level security;
alter table public.reports enable row level security;

do $$ begin
 create policy "beta profiles" on public.profiles for all to anon,authenticated using(true) with check(true);
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "beta admins read" on public.admin_users for select to anon,authenticated using(true);
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "beta fares" on public.fare_settings for all to anon,authenticated using(true) with check(true);
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "beta events" on public.ride_events for all to anon,authenticated using(true) with check(true);
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "beta reports" on public.reports for all to anon,authenticated using(true) with check(true);
exception when duplicate_object then null; end $$;

-- Realtime para operación administrativa.
do $$ begin alter publication supabase_realtime add table public.fare_settings; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.reports; exception when duplicate_object then null; end $$;
